const DEFAULT_CATEGORIES={expense:[['餐饮','🍜'],['购物','🛍️'],['日用','🧻'],['交通','🚌'],['蔬菜','🥕'],['水果','🍎'],['零食','🧁'],['运动','🚲'],['娱乐','🎤'],['通讯','📞'],['服饰','👕'],['住房','🏠'],['孩子','🧸'],['长辈','👴'],['社交','💬'],['旅行','✈️'],['医疗','🩹'],['学习','🎓'],['礼金','💴'],['礼物','🎁'],['快递','📦'],['工作创业','🎮'],['租房','🛏️'],['美团','🍸'],['借款','🪙'],['汽车','🚗'],['人情往来','👥'],['养老保险','🛟'],['其他','⚙️']],income:[['工资','💴'],['兼职','⏱️'],['理财','📈'],['礼金','🧧'],['其他','🪙'],['刘佳勇','🔄'],['自媒体','🖥️'],['刘语航','🐷'],['设置','⚙️']]};
const $=s=>document.querySelector(s); const dataKey='jingzhang-v1';
const historyStyle=document.createElement('style');historyStyle.textContent=`#monthPicker{width:118px;padding:7px 8px;border-radius:10px;border:1px solid #dfe5ef;background:#fff;color:#3478f6;font-size:13px;font-weight:700}.list-actions{display:flex;gap:12px}.trend-wrap{background:#f7f9fd;border-radius:16px;padding:13px;margin:10px 0 20px}.trend-head{display:flex;align-items:center;justify-content:space-between}.trend-head h3{margin:0!important}.trend-head span{font-size:11px;color:#77809a}#trendChart{display:block;width:100%;height:150px;margin-top:8px}`;document.head.append(historyStyle);
const extraStyle=document.createElement('style');extraStyle.textContent=`.header-actions{display:flex;align-items:center;gap:8px}.book-button{background:#edf3ff;color:#3478f6;border-radius:99px;padding:8px 10px;font-size:12px;font-weight:800;max-width:130px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.report-tabs{display:grid;grid-template-columns:1fr 1fr;border:1px solid #dfe5f0;border-radius:11px;overflow:hidden;margin:14px 0}.report-tabs button{background:#fff;color:#68748a;padding:9px;font-weight:800}.report-tabs button.active{background:#3478f6;color:#fff}.book-list{display:grid;gap:10px;margin:15px 0}.book-card{display:flex;align-items:center;gap:10px;padding:13px;border:1px solid #e3e8f1;border-left:7px solid var(--book-color);background:#fff;border-radius:13px;color:#263451;text-align:left}.book-card i{font-style:normal;border-radius:9px;background:#eef3ff;color:var(--book-color);font-weight:900;padding:7px 9px}.book-card span{font-weight:800;flex:1}.book-card b{font-size:11px;color:#3478f6}.book-card.active{background:#f5f8ff;border-color:#a9c5ff}.book-add-row{display:grid;grid-template-columns:1fr 42px auto;gap:8px;margin-top:12px}.book-add-row input{min-width:0;padding:10px;border:1px solid #dfe5f0;border-radius:10px}.book-add-row input[type=color]{padding:3px}`;document.head.append(extraStyle);
const reportStyle=document.createElement('style');reportStyle.textContent=`.bill-picker{display:flex;align-items:center;justify-content:space-between;background:#f3f6fb;border-radius:12px;padding:8px 10px;margin:12px 0}.bill-picker span{font-size:12px;color:#66728a;font-weight:700}.bill-picker select{width:auto;border:0;background:transparent;font-weight:800;color:#253452;padding:4px}.bill-table-head,.bill-row{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:5px;align-items:center}.bill-table-head{color:#8a94a7;font-size:11px;padding:8px 7px}.bill-row{width:100%;padding:15px 7px;border-top:1px solid #edf0f5;background:#fff;text-align:left;color:#2a3448;font-weight:700}.bill-row b{font-size:12px}.bill-row span{font-size:12px}.bill-row:after{content:'›';color:#9ba4b4;font-size:22px;text-align:right}.bill-table-wrap{margin-top:5px}.chart-periods{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid #dce3ef;border-radius:9px;overflow:hidden;margin:9px 0}.chart-periods button{padding:7px;background:#fff;color:#68748a;font-weight:800}.chart-periods button.active{background:#26314b;color:#fff}`;document.head.append(reportStyle);
let state=JSON.parse(localStorage.getItem(dataKey)||'{"transactions":[],"settings":{"currency":"¥","budget":""}}');state.settings??={currency:'¥',budget:''};state.categories??=JSON.parse(JSON.stringify(DEFAULT_CATEGORIES));state.accounts??=[['微信','💬'],['支付宝','🔵'],['银行卡','💳'],['现金','💵']];state.books??=[{id:'family',name:'家庭账本',color:'#ffd936'}];state.currentBookId??=state.books[0].id;for(const type of ['expense','income'])for(const item of DEFAULT_CATEGORIES[type])if(!state.categories[type].some(c=>c[0]===item[0]))state.categories[type].push(item);
let currentMonth=new Date(); currentMonth.setDate(1); let editId=null, entryType='expense', filter='all', accountFilter='all', listMode='month';
const save=()=>localStorage.setItem(dataKey,JSON.stringify(state));save();
const id=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const money=n=>`${state.settings.currency||'¥'}${Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateText=d=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${d}T12:00:00`));
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const categoryList=type=>state.categories[type]||DEFAULT_CATEGORIES[type];
const accountList=()=>state.accounts||[];
const activeBook=()=>state.books.find(book=>book.id===state.currentBookId)||state.books[0];
const iconFor=(type,category)=>categoryList(type).find(c=>c[0]===category)?.[1]||'🧾';
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function belongsToActiveBook(t){return (t.bookId||'family')===activeBook().id}
function monthTransactions(){return state.transactions.filter(t=>belongsToActiveBook(t)&&(listMode==='all'||t.date.startsWith(monthKey(currentMonth)))).filter(t=>filter==='all'||t.type===filter).filter(t=>accountFilter==='all'||t.account===accountFilter).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)}
function render(){
  $('#monthLabel').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long'}).format(currentMonth);$('#monthPicker').value=monthKey(currentMonth);$('#bookTitle').textContent=activeBook().name;$('#bookButton').textContent=`${activeBook().name}⌄`;$('#listTitle').textContent=listMode==='all'?'全部历史流水':'本月流水';$('#allHistoryButton').textContent=listMode==='all'?'返回本月':'全部历史';
  const all=state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(monthKey(currentMonth))); const income=all.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0), expense=all.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);
  $('#incomeAmount').textContent=money(income);$('#expenseAmount').textContent=money(expense);$('#balanceAmount').textContent=money(income-expense);
  $('#accountHint').textContent=accountFilter==='all'?'全部账户':accountFilter;
  $('#accountChips').innerHTML=`<button class="account-chip ${accountFilter==='all'?'active':''}" data-account="all">全部</button>`+accountList().map(([name,icon])=>`<button class="account-chip ${accountFilter===name?'active':''}" data-account="${name}">${icon} ${name}</button>`).join('');
  const budget=Number(state.settings.budget||0);$('#budgetLine').hidden=!budget;if(budget){const percent=Math.round(expense/budget*100);$('#budgetText').textContent=`本月预算 ${money(budget)} · 已用 ${percent}%`;$('#budgetProgress').style.width=`${Math.min(percent,100)}%`;}
  const byCategory={};all.filter(t=>t.type==='expense').forEach(t=>byCategory[t.category]=(byCategory[t.category]||0)+t.amount);const ranked=Object.entries(byCategory).sort((a,b)=>b[1]-a[1]).slice(0,5);$('#categorySummary').hidden=!ranked.length;$('#categoryTotal').textContent=`共 ${money(expense)}`;$('#categoryBars').innerHTML=ranked.map(([name,value])=>`<div class="category-bar"><i>${iconFor('expense',name)}</i><div class="category-bar-main"><span class="category-bar-label"><span>${name}</span><b>${money(value)}</b></span><span class="category-track"><span style="width:${Math.round(value/expense*100)}%"></span></span></div><span>${Math.round(value/expense*100)}%</span></div>`).join('');
  const days=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+1,0).getDate();$('#dailyExpense').textContent=money(expense/days);$('#transactionCount').textContent=`${all.length} 笔`;
  const max=all.filter(t=>t.type==='expense').sort((a,b)=>b.amount-a.amount)[0];$('#largestExpense').textContent=max?money(max.amount):'—';
  const list=$('#transactionList'); list.innerHTML=''; const groups={}; monthTransactions().forEach(t=>(groups[t.date]??=[]).push(t));
  Object.entries(groups).forEach(([date,items])=>{const group=document.createElement('div');group.className='day-group'; const total=items.reduce((s,t)=>s+(t.type==='expense'?-t.amount:t.amount),0);group.innerHTML=`<div class="day-header"><span>${dateText(date)}</span><span>${total>=0?'+':''}${money(total)}</span></div>`;items.forEach(t=>{const row=document.createElement('button');row.className='transaction';row.dataset.id=t.id;row.innerHTML=`<span class="category-icon">${iconFor(t.type,t.category)}</span><span><span class="transaction-name">${t.category}</span><span class="transaction-note">${t.note|| (t.type==='income'?'收入':'支出')} · ${t.account||'未选择账户'}</span></span><span class="transaction-amount ${t.type}">${t.type==='income'?'+':'-'}${money(t.amount)}</span>`;group.append(row)});list.append(group)});
  const visible=monthTransactions();$('#emptyState').hidden=visible.length>0; list.hidden=visible.length===0;
}
function fillCategories(type,selected){const active=selected||categoryList(type)[0][0];$('#categoryInput').innerHTML=categoryList(type).map(([name,emoji])=>`<option value="${name}" ${name===active?'selected':''}>${emoji} ${name}</option>`).join('');$('#categoryGrid').innerHTML=categoryList(type).map(([name,emoji])=>`<button type="button" class="category-choice ${name===active?'selected':''}" data-category="${name}"><span>${emoji}</span><b>${name}</b></button>`).join('')}
function fillAccounts(selected){const active=selected||accountList()[0]?.[0]||'';$('#accountInput').innerHTML=accountList().map(([name,icon])=>`<option value="${name}" ${name===active?'selected':''}>${icon} ${name}</option>`).join('')}
function renderCategoryManager(){for(const type of ['expense','income']){$(`#${type}CategoryManager`).innerHTML=categoryList(type).map(([name,icon])=>`<span class="managed-category">${icon} ${name}<button type="button" data-type="${type}" data-name="${name}" aria-label="删除 ${name}">×</button></span>`).join('')}}
function renderAccountManager(){const manager=$('#accountManager');manager.innerHTML=accountList().map(([name,icon])=>`<span class="managed-category">${icon} ${name}<button type="button" data-account-name="${name}" aria-label="删除 ${name}">×</button></span>`).join('')}
function openEntry(t){editId=t?.id||null;entryType=t?.type||'expense';$('#formTitle').textContent=t?'修改账目':'记一笔';$('#amountInput').value=t?.amount||'';$('#dateInput').value=t?.date||new Date().toISOString().slice(0,10);$('#noteInput').value=t?.note||'';fillCategories(entryType,t?.category);fillAccounts(t?.account);document.querySelectorAll('.type-option').forEach(b=>b.classList.toggle('active',b.dataset.type===entryType));$('#deleteButton').hidden=!t;$('#transactionDialog').showModal();setTimeout(()=>$('#amountInput').focus(),100)}
$('#addButton').onclick=()=>openEntry(); $('#transactionList').onclick=e=>{const row=e.target.closest('.transaction');if(row)openEntry(state.transactions.find(t=>t.id===row.dataset.id))};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
document.querySelectorAll('.type-option').forEach(b=>b.onclick=()=>{entryType=b.dataset.type;fillCategories(entryType);document.querySelectorAll('.type-option').forEach(x=>x.classList.toggle('active',x===b))});
$('#categoryGrid').onclick=e=>{const choice=e.target.closest('.category-choice');if(!choice)return;$('#categoryInput').value=choice.dataset.category;document.querySelectorAll('.category-choice').forEach(b=>b.classList.toggle('selected',b===choice))};
$('#transactionForm').onsubmit=e=>{e.preventDefault();const amount=Number($('#amountInput').value);if(!amount||amount<0){toast('请输入正确的金额');return} const previous=editId?state.transactions.find(t=>t.id===editId):null;const record={id:editId||id(),type:entryType,amount,category:$('#categoryInput').value,account:$('#accountInput').value,date:$('#dateInput').value,note:$('#noteInput').value.trim(),bookId:previous?.bookId||activeBook().id,createdAt:previous?.createdAt||Date.now()};if(editId)state.transactions=state.transactions.map(t=>t.id===editId?record:t);else state.transactions.push(record);save();$('#transactionDialog').close();render();toast(editId?'已更新':'已记下这笔账')};
$('#deleteButton').onclick=()=>{state.transactions=state.transactions.filter(t=>t.id!==editId);save();$('#transactionDialog').close();render();toast('已删除')};
$('#previousMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()-1);listMode='month';render()};$('#nextMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()+1);listMode='month';render()};
$('#monthPicker').onchange=e=>{if(!e.target.value)return;currentMonth=new Date(`${e.target.value}-01T12:00:00`);listMode='month';render()};
$('#allHistoryButton').onclick=()=>{listMode=listMode==='all'?'month':'all';render()};
function openSettings(){$('#currencyInput').value=state.settings.currency||'¥';$('#budgetInput').value=state.settings.budget||'';renderCategoryManager();renderAccountManager();$('#settingsDialog').showModal()}
function renderBooks(){const list=$('#bookList');list.innerHTML=state.books.map(book=>`<button class="book-card ${book.id===activeBook().id?'active':''}" data-book-id="${book.id}" style="--book-color:${book.color}"><i>¥</i><span>${book.name}</span>${book.id===activeBook().id?'<b>当前</b>':''}</button>`).join('')}
function openBooks(){renderBooks();$('#bookDialog').showModal()}
$('#bookButton').onclick=openBooks;
$('#bookList').onclick=e=>{const card=e.target.closest('[data-book-id]');if(!card)return;state.currentBookId=card.dataset.bookId;accountFilter='all';save();$('#bookDialog').close();render();toast(`已切换到${activeBook().name}`)};
$('#addBook').onclick=()=>{const name=$('#newBookName').value.trim(),color=$('#newBookColor').value;if(!name){toast('先填写账本名称');return}if(state.books.some(book=>book.name===name)){toast('这个账本已经有了');return}state.books.push({id:id(),name,color});state.currentBookId=state.books[state.books.length-1].id;$('#newBookName').value='';save();$('#bookDialog').close();render();toast('新账本已创建')};
$('#settingsButton').onclick=openSettings;$('#navSettings').onclick=openSettings;
$('#saveSettings').onclick=()=>{state.settings.currency=$('#currencyInput').value.trim()||'¥';state.settings.budget=$('#budgetInput').value;save();$('#settingsDialog').close();render();toast('设置已保存')};
$('#addCategory').onclick=()=>{const type=$('#newCategoryType').value,name=$('#newCategoryName').value.trim(),icon=$('#newCategoryIcon').value.trim()||'🏷️';if(!name){toast('先填写分类名称');return}if(categoryList(type).some(c=>c[0]===name)){toast('这个分类已经有了');return}state.categories[type].push([name,icon]);save();$('#newCategoryName').value='';renderCategoryManager();toast('已添加分类')};
for(const manager of [$('#expenseCategoryManager'),$('#incomeCategoryManager')])manager.onclick=e=>{const b=e.target.closest('button');if(!b)return;const {type,name}=b.dataset;if(state.transactions.some(t=>t.type===type&&t.category===name)){toast('已有账目使用该分类，暂不能删除');return}state.categories[type]=categoryList(type).filter(c=>c[0]!==name);save();renderCategoryManager();toast(`已删除“${name}”`)};
$('#addAccount').onclick=()=>{const name=$('#newAccountName').value.trim(),icon=$('#newAccountIcon').value.trim()||'💳';if(!name){toast('先填写账户名称');return}if(accountList().some(a=>a[0]===name)){toast('这个账户已经有了');return}state.accounts.push([name,icon]);save();$('#newAccountName').value='';renderAccountManager();render();toast('已添加账户')};
$('#accountManager').onclick=e=>{const b=e.target.closest('button');const name=b?.dataset.accountName;if(!name)return;if(state.transactions.some(t=>t.account===name)){toast('已有账目使用该账户，暂不能删除');return}state.accounts=accountList().filter(a=>a[0]!==name);if(accountFilter===name)accountFilter='all';save();renderAccountManager();render();toast('已删除账户')};
$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`简账备份-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('备份已导出')};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported.transactions))throw Error();state=imported;save();$('#settingsDialog').close();render();toast('备份导入成功')}catch{toast('这不是有效的简账备份文件')}e.target.value=''};
$('#filterButton').onclick=()=>$('#filterDialog').showModal();$('#filterOptions').onclick=e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;document.querySelectorAll('#filterOptions button').forEach(b=>b.classList.toggle('active',b===e.target));$('#filterDialog').close();render()};
$('#accountChips').onclick=e=>{const chip=e.target.closest('[data-account]');if(!chip)return;accountFilter=chip.dataset.account;render()};
let reportMode='month';
function reportTransactions(){const year=String(currentMonth.getFullYear());return state.transactions.filter(t=>belongsToActiveBook(t)&&(reportMode==='year'?t.date.startsWith(year):t.date.startsWith(monthKey(currentMonth))))}
function drawTrend(){const chart=$('#trendChart'),ctx=chart.getContext('2d'),year=currentMonth.getFullYear(),values=Array.from({length:12},(_,i)=>state.transactions.filter(t=>belongsToActiveBook(t)&&t.type==='expense'&&t.date.startsWith(`${year}-${String(i+1).padStart(2,'0')}`)).reduce((s,t)=>s+t.amount,0)),max=Math.max(...values,1),width=chart.clientWidth*devicePixelRatio,height=150*devicePixelRatio;chart.width=width;chart.height=height;ctx.scale(devicePixelRatio,devicePixelRatio);const w=chart.clientWidth,h=150,pad=18;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#dfe6f3';ctx.lineWidth=1;[0,1,2].forEach(i=>{const y=pad+(h-pad*2)*i/2;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()});ctx.strokeStyle='#3478f6';ctx.lineWidth=2.5;ctx.beginPath();values.forEach((v,i)=>{const x=pad+(w-pad*2)*i/11,y=h-pad-(v/max)*(h-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();values.forEach((v,i)=>{const x=pad+(w-pad*2)*i/11,y=h-pad-(v/max)*(h-pad*2);ctx.fillStyle='#3478f6';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();if(i%2===0){ctx.fillStyle='#77809a';ctx.font='10px sans-serif';ctx.fillText(`${i+1}月`,x-8,h-3)}});$('#trendHint').textContent=`最高 ${money(Math.max(...values))}`}
function openLegacyReport(){const all=reportTransactions();const income=all.filter(t=>t.type==='income').reduce((sum,t)=>sum+t.amount,0),expense=all.filter(t=>t.type==='expense').reduce((sum,t)=>sum+t.amount,0);const ranked=Object.entries(all.filter(t=>t.type==='expense').reduce((map,t)=>{map[t.category]=(map[t.category]||0)+t.amount;return map},{})).sort((a,b)=>b[1]-a[1]);const title=reportMode==='year'?`${currentMonth.getFullYear()}年账单`:new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long'}).format(currentMonth)+'统计';$('#reportEyebrow').textContent=reportMode==='year'?'年度回顾':'月度回顾';$('#reportMonth').textContent=title;$('#reportBalance').textContent=money(income-expense);$('#reportIncome').textContent=money(income);$('#reportExpense').textContent=money(expense);$('#reportDays').textContent=reportMode==='year'?`${new Set(all.map(t=>t.date.slice(0,7))).size} 个月`:`${new Set(all.map(t=>t.date)).size} 天`;$('#trendWrap').hidden=reportMode!=='year';$('#reportRanks').innerHTML=ranked.length?ranked.slice(0,6).map(([name,value])=>`<div class="report-rank"><i>${iconFor('expense',name)}</i><div><b>${name}</b><div class="report-rank-bar"><span style="width:${Math.round(value/expense*100)}%"></span></div></div><strong>${money(value)}</strong></div>`).join(''):`<p class="settings-note">${reportMode==='year'?'这一年':'这个月'}还没有支出记录。</p>`;document.querySelectorAll('[data-report-mode]').forEach(b=>b.classList.toggle('active',b.dataset.reportMode===reportMode));$('#reportDialog').showModal();if(reportMode==='year')requestAnimationFrame(drawTrend)}
let chartPeriod='year';
const reportYears=()=>[...new Set([currentMonth.getFullYear(),...state.transactions.filter(belongsToActiveBook).map(t=>Number(t.date.slice(0,4)))])].sort((a,b)=>b-a);
const totals=items=>({income:items.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),expense:items.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0)});
function chartSeries(){const year=currentMonth.getFullYear(),today=new Date(),items=state.transactions.filter(belongsToActiveBook);if(chartPeriod==='year')return Array.from({length:12},(_,i)=>({label:`${i+1}月`,value:items.filter(t=>t.type==='expense'&&t.date.startsWith(`${year}-${String(i+1).padStart(2,'0')}`)).reduce((s,t)=>s+t.amount,0)}));if(chartPeriod==='month'){const count=new Date(year,currentMonth.getMonth()+1,0).getDate();return Array.from({length:count},(_,i)=>({label:`${i+1}`,value:items.filter(t=>t.type==='expense'&&t.date===`${monthKey(currentMonth)}-${String(i+1).padStart(2,'0')}`).reduce((s,t)=>s+t.amount,0)}))}return Array.from({length:7},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-6+i);const key=d.toISOString().slice(0,10);return{label:`${d.getMonth()+1}/${d.getDate()}`,value:items.filter(t=>t.type==='expense'&&t.date===key).reduce((s,t)=>s+t.amount,0)}})}
function drawRichTrend(){const series=chartSeries(),chart=$('#trendChart'),ctx=chart.getContext('2d'),max=Math.max(...series.map(x=>x.value),1),width=chart.clientWidth*devicePixelRatio,height=150*devicePixelRatio;chart.width=width;chart.height=height;ctx.scale(devicePixelRatio,devicePixelRatio);const w=chart.clientWidth,h=150,pad=18;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#dfe6f3';[0,1,2].forEach(i=>{const y=pad+(h-pad*2)*i/2;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()});ctx.strokeStyle='#3478f6';ctx.lineWidth=2.5;ctx.beginPath();series.forEach((p,i)=>{const x=pad+(w-pad*2)*(series.length===1?0:i/(series.length-1)),y=h-pad-(p.value/max)*(h-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();series.forEach((p,i)=>{const x=pad+(w-pad*2)*(series.length===1?0:i/(series.length-1)),y=h-pad-(p.value/max)*(h-pad*2);ctx.fillStyle='#3478f6';ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fill();if(i===0||i===series.length-1||series.length<=12&&i%2===0){ctx.fillStyle='#77809a';ctx.font='10px sans-serif';ctx.fillText(p.label,x-8,h-3)}});$('#trendHint').textContent=`最高 ${money(max)}`}
function renderBillRows(year){if(reportMode==='month'){const rows=Array.from({length:12},(_,i)=>{const month=11-i,items=state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)),sum=totals(items);return{label:`${month+1}月`,income:sum.income,expense:sum.expense,balance:sum.income-sum.expense,month}});$('#billTableHead').innerHTML='<span>月份</span><span>月收入</span><span>月支出</span><span>月结余</span>';$('#billRows').innerHTML=rows.map(r=>`<button class="bill-row" data-bill-month="${r.month}"><span>${r.label}</span><b>${money(r.income)}</b><b>${money(r.expense)}</b><b>${money(r.balance)}</b></button>`).join('')}else{const rows=reportYears().map(y=>{const sum=totals(state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(String(y))));return{year:y,income:sum.income,expense:sum.expense,balance:sum.income-sum.expense}});$('#billTableHead').innerHTML='<span>年份</span><span>年收入</span><span>年支出</span><span>年结余</span>';$('#billRows').innerHTML=rows.map(r=>`<button class="bill-row" data-bill-year="${r.year}"><span>${r.year}年</span><b>${money(r.income)}</b><b>${money(r.expense)}</b><b>${money(r.balance)}</b></button>`).join('')}}
function openReport(){const year=currentMonth.getFullYear(),yearItems=state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(String(year))),shown=reportMode==='year'?state.transactions.filter(belongsToActiveBook):reportMode==='chart'?yearItems:yearItems,sum=totals(shown),ranked=Object.entries(shown.filter(t=>t.type==='expense').reduce((map,t)=>{map[t.category]=(map[t.category]||0)+t.amount;return map},{})).sort((a,b)=>b[1]-a[1]);$('#reportYearPicker').innerHTML=reportYears().map(y=>`<option value="${y}" ${y===year?'selected':''}>${y}年</option>`).join('');$('#billPicker').hidden=reportMode==='chart';$('#reportEyebrow').textContent=reportMode==='chart'?'收支图表':reportMode==='year'?'年度总账':'年度月账单';$('#reportMonth').textContent=reportMode==='chart'?`${year}年支出分析`:reportMode==='year'?'所有年份账单':`${year}年账单`;$('#reportBalance').textContent=money(sum.income-sum.expense);$('#reportIncome').textContent=money(sum.income);$('#reportExpense').textContent=money(sum.expense);$('#reportDays').textContent=reportMode==='chart'?`${new Set(shown.map(t=>t.date.slice(0,7))).size} 个月`:`${shown.length} 笔`;$('#trendWrap').hidden=reportMode!=='chart';$('#billTableWrap').hidden=reportMode==='chart';$('#rankWrap').hidden=reportMode!=='chart';if(reportMode!=='chart')renderBillRows(year);else requestAnimationFrame(drawRichTrend);$('#reportRanks').innerHTML=ranked.length?ranked.slice(0,6).map(([name,value])=>`<div class="report-rank"><i>${iconFor('expense',name)}</i><div><b>${name}</b><div class="report-rank-bar"><span style="width:${Math.round(value/sum.expense*100)}%"></span></div></div><strong>${money(value)}</strong></div>`).join(''):'<p class="settings-note">还没有支出记录。</p>';document.querySelectorAll('[data-report-mode]').forEach(b=>b.classList.toggle('active',b.dataset.reportMode===reportMode));$('#reportDialog').showModal()}
document.querySelectorAll('[data-report-mode]').forEach(b=>b.onclick=()=>{reportMode=b.dataset.reportMode;openReport()});
$('#reportYearPicker').onchange=e=>{currentMonth.setFullYear(Number(e.target.value));openReport()};
$('#billRows').onclick=e=>{const row=e.target.closest('[data-bill-month],[data-bill-year]');if(!row)return;if(row.dataset.billMonth!==undefined){currentMonth.setMonth(Number(row.dataset.billMonth));reportMode='chart';}else currentMonth.setFullYear(Number(row.dataset.billYear));openReport()};
document.querySelectorAll('[data-chart-period]').forEach(b=>b.onclick=()=>{chartPeriod=b.dataset.chartPeriod;document.querySelectorAll('[data-chart-period]').forEach(x=>x.classList.toggle('active',x===b));drawRichTrend()});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='report')openReport()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');render();
