const DEFAULT_CATEGORIES={expense:[['餐饮','🍜'],['购物','🛍️'],['日用','🧻'],['交通','🚌'],['蔬菜','🥕'],['水果','🍎'],['零食','🧁'],['运动','🚲'],['娱乐','🎤'],['通讯','📞'],['服饰','👕'],['住房','🏠'],['孩子','🧸'],['长辈','👴'],['社交','💬'],['旅行','✈️'],['医疗','🩹'],['学习','🎓'],['礼金','💴'],['礼物','🎁'],['快递','📦'],['工作创业','🎮'],['租房','🛏️'],['美团','🍸'],['借款','🪙'],['汽车','🚗'],['人情往来','👥'],['养老保险','🛟'],['其他','⚙️']],income:[['工资','💴'],['兼职','⏱️'],['理财','📈'],['礼金','🧧'],['其他','🪙'],['刘佳勇','🔄'],['自媒体','🖥️'],['刘语航','🐷'],['设置','⚙️']]};
const $=s=>document.querySelector(s); const dataKey='jingzhang-v1';
let state=JSON.parse(localStorage.getItem(dataKey)||'{"transactions":[],"settings":{"currency":"¥","budget":""}}');state.settings??={currency:'¥',budget:''};state.categories??=JSON.parse(JSON.stringify(DEFAULT_CATEGORIES));state.accounts??=[['微信','💬'],['支付宝','🔵'],['银行卡','💳'],['现金','💵']];state.books??=[{id:'family',name:'家庭账本',color:'#ffd936'}];state.currentBookId??=state.books[0].id;
state.monthlyBudgets??={};
let currentMonth=new Date(); currentMonth.setDate(1); let editId=null, entryType='expense', filter='all', accountFilter='all', listMode='month';
if(state.settings.budget){state.monthlyBudgets[state.currentBookId]??={};state.monthlyBudgets[state.currentBookId][`${currentMonth.getFullYear()}-${String(currentMonth.getMonth()+1).padStart(2,'0')}`]??=state.settings.budget;state.settings.budget=''}
const save=()=>localStorage.setItem(dataKey,JSON.stringify(state));save();
const id=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const money=n=>`${state.settings.currency||'¥'}${Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateText=d=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${d}T12:00:00`));
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const budgetForMonth=()=>Number(state.monthlyBudgets?.[activeBook().id]?.[monthKey(currentMonth)] ?? 0);
const categoryList=type=>state.categories[type]||DEFAULT_CATEGORIES[type];
const accountList=()=>state.accounts||[];
const activeBook=()=>state.books.find(book=>book.id===state.currentBookId)||state.books[0];
const iconFor=(type,category)=>categoryList(type).find(c=>c[0]===category)?.[1]||'🧾';
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function belongsToActiveBook(t){return (t.bookId||'family')===activeBook().id}
function monthTransactions(){return state.transactions.filter(t=>belongsToActiveBook(t)&&(listMode==='all'||t.date.startsWith(monthKey(currentMonth)))).filter(t=>filter==='all'||t.type===filter).filter(t=>accountFilter==='all'||t.account===accountFilter).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)}
function render(){
  $('#monthLabel').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long'}).format(currentMonth);$('#monthPicker').value=monthKey(currentMonth);$('#bookTitle').textContent='Sunny记账';$('#bookButton').textContent=`${activeBook().name}⌄`;$('#listTitle').textContent=listMode==='all'?'全部历史流水':'本月流水';$('#allHistoryButton').textContent=listMode==='all'?'返回本月':'全部历史';
  const all=state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(monthKey(currentMonth))); const income=all.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0), expense=all.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);
  $('#incomeAmount').textContent=money(income);$('#expenseAmount').textContent=money(expense);$('#balanceAmount').textContent=money(income-expense);
  $('#accountHint').textContent=accountFilter==='all'?'全部账户':accountFilter;
  $('#accountChips').innerHTML=`<button class="account-chip ${accountFilter==='all'?'active':''}" data-account="all">全部</button>`+accountList().map(([name,icon])=>`<button class="account-chip ${accountFilter===name?'active':''}" data-account="${name}">${icon} ${name}</button>`).join('');
  const budget=budgetForMonth();$('#budgetLine').hidden=!budget;if(budget){const percent=Math.round(expense/budget*100);$('#budgetText').textContent=`本月预算 ${money(budget)} · 已用 ${percent}%`;$('#budgetProgress').style.width=`${Math.min(percent,100)}%`;}
  const byCategory={};all.filter(t=>t.type==='expense').forEach(t=>byCategory[t.category]=(byCategory[t.category]||0)+t.amount);const ranked=Object.entries(byCategory).sort((a,b)=>b[1]-a[1]).slice(0,5);$('#categorySummary').hidden=!ranked.length;$('#categoryTotal').textContent=`共 ${money(expense)}`;$('#categoryBars').innerHTML=ranked.map(([name,value])=>`<div class="category-bar"><i>${iconFor('expense',name)}</i><div class="category-bar-main"><span class="category-bar-label"><span>${name}</span><b>${money(value)}</b></span><span class="category-track"><span style="width:${Math.round(value/expense*100)}%"></span></span></div><span>${Math.round(value/expense*100)}%</span></div>`).join('');
  const days=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+1,0).getDate();$('#dailyExpense').textContent=money(expense/days);$('#transactionCount').textContent=`${all.length} 笔`;
  const max=all.filter(t=>t.type==='expense').sort((a,b)=>b.amount-a.amount)[0];$('#largestExpense').textContent=max?money(max.amount):'—';
  const list=$('#transactionList'); list.innerHTML=''; const groups={}; monthTransactions().forEach(t=>(groups[t.date]??=[]).push(t));
  Object.entries(groups).forEach(([date,items])=>{const group=document.createElement('div');group.className='day-group'; const total=items.reduce((s,t)=>s+(t.type==='expense'?-t.amount:t.amount),0);group.innerHTML=`<div class="day-header"><span>${dateText(date)}</span><span>${total>=0?'+':''}${money(total)}</span></div>`;items.forEach(t=>{const row=document.createElement('button');row.className='transaction';row.dataset.id=t.id;row.innerHTML=`<span class="category-icon">${iconFor(t.type,t.category)}</span><span><span class="transaction-name">${t.category}</span><span class="transaction-note">${t.note|| (t.type==='income'?'收入':'支出')} · ${t.account||'未选择账户'}</span></span><span class="transaction-amount ${t.type}">${t.type==='income'?'+':'-'}${money(t.amount)}</span>`;group.append(row)});list.append(group)});
  const visible=monthTransactions();$('#emptyState').hidden=visible.length>0; list.hidden=visible.length===0;
}
function fillCategories(type,selected){const active=selected||categoryList(type)[0][0];$('#categoryInput').innerHTML=categoryList(type).map(([name,emoji])=>`<option value="${name}" ${name===active?'selected':''}>${emoji} ${name}</option>`).join('');$('#categoryGrid').innerHTML=categoryList(type).map(([name,emoji])=>`<button type="button" class="category-choice ${name===active?'selected':''}" data-category="${name}"><span>${emoji}</span><b>${name}</b></button>`).join('')}
function fillAccounts(selected){const active=selected||accountList()[0]?.[0]||'';$('#accountInput').innerHTML=accountList().map(([name,icon])=>`<option value="${name}" ${name===active?'selected':''}>${icon} ${name}</option>`).join('')}
function renderCategoryManager(){for(const type of ['expense','income']){$(`#${type}CategoryManager`).innerHTML=categoryList(type).map(([name,icon])=>`<span class="managed-category">${icon} ${name}<button type="button" data-type="${type}" data-name="${name}" aria-label="删除 ${name}">×</button></span>`).join('')}}
function renderAccountManager(){const manager=$('#accountManager');manager.innerHTML=accountList().map(([name,icon])=>`<span class="managed-category">${icon} ${name}<button type="button" data-account-name="${name}" aria-label="删除 ${name}">×</button></span>`).join('')}
function openEntry(t){editId=t?.id||null;entryType=t?.type||'expense';$('#formTitle').textContent=t?'修改账目':'记一笔';$('#amountInput').value=t?.amount||'';$('#dateInput').value=t?.date||new Date().toISOString().slice(0,10);$('#noteInput').value=t?.note||'';fillCategories(entryType,t?.category);fillAccounts(t?.account);document.querySelectorAll('.type-option').forEach(b=>b.classList.toggle('active',b.dataset.type===entryType));$('#deleteButton').hidden=!t;$('#transactionDialog').showModal();setTimeout(()=>$('#amountInput').focus(),100)}
$('#addButton').onclick=()=>openEntry(); $('#transactionList').onclick=e=>{const row=e.target.closest('.transaction');if(row)openEntry(state.transactions.find(t=>t.id===row.dataset.id))};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
document.querySelectorAll('.type-option').forEach(b=>b.onclick=()=>{entryType=b.dataset.type;fillCategories(entryType);document.querySelectorAll('.type-option').forEach(x=>x.classList.toggle('active',x===b))});
$('#categoryGrid').onclick=e=>{const choice=e.target.closest('.category-choice');if(!choice)return;$('#categoryInput').value=choice.dataset.category;document.querySelectorAll('.category-choice').forEach(b=>b.classList.toggle('selected',b===choice))};
$('#transactionForm').onsubmit=e=>{e.preventDefault();const amount=Number($('#amountInput').value);if(!amount||amount<0){toast('请输入正确的金额');return} const previous=editId?state.transactions.find(t=>t.id===editId):null;const record={id:editId||id(),type:entryType,amount,category:$('#categoryInput').value,account:$('#accountInput').value,date:$('#dateInput').value,note:$('#noteInput').value.trim(),bookId:previous?.bookId||activeBook().id,createdAt:previous?.createdAt||Date.now()};if(editId)state.transactions=state.transactions.map(t=>t.id===editId?record:t);else state.transactions.push(record);save();$('#transactionDialog').close();render();toast(editId?'已更新':'已记下这笔账')};
$('#deleteButton').onclick=()=>{state.transactions=state.transactions.filter(t=>t.id!==editId);save();$('#transactionDialog').close();render();toast('已删除')};
$('#previousMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()-1);listMode='month';render()};$('#nextMonth').onclick=()=>{currentMonth.setMonth(currentMonth.getMonth()+1);listMode='month';render()};
$('#monthPicker').onchange=e=>{if(!e.target.value)return;currentMonth=new Date(`${e.target.value}-01T12:00:00`);listMode='month';render()};
$('#allHistoryButton').onclick=()=>{listMode=listMode==='all'?'month':'all';render()};
function selectableYears(){const now=new Date().getFullYear(),recordYears=state.transactions.map(t=>Number(t.date.slice(0,4))).filter(Boolean),first=Math.min(now-20,...recordYears,currentMonth.getFullYear()),last=Math.max(now+1,...recordYears,currentMonth.getFullYear());return Array.from({length:last-first+1},(_,i)=>last-i)}
function openHistory(){const year=$('#historyYear');year.innerHTML=selectableYears().map(y=>`<option value="${y}" ${y===currentMonth.getFullYear()?'selected':''}>${y}年</option>`).join('');renderHistoryMonths();$('#historyDialog').showModal()}
function renderHistoryMonths(){const year=Number($('#historyYear').value||currentMonth.getFullYear());$('#historyMonths').innerHTML=Array.from({length:12},(_,i)=>`<button type="button" data-history-month="${i}" class="${year===currentMonth.getFullYear()&&i===currentMonth.getMonth()?'active':''}">${i+1}月</button>`).join('')}
$('#monthLabel').onclick=openHistory;
$('#historyYear').onchange=renderHistoryMonths;
$('#historyMonths').onclick=e=>{const button=e.target.closest('[data-history-month]');if(!button)return;currentMonth=new Date(Number($('#historyYear').value),Number(button.dataset.historyMonth),1);listMode='month';$('#historyDialog').close();render()};
$('#showAllHistory').onclick=()=>{listMode='all';$('#historyDialog').close();render()};
function openSettings(){$('#currencyInput').value=state.settings.currency||'¥';$('#budgetInput').value=budgetForMonth()||'';$('#budgetLabel').textContent=`${monthKey(currentMonth).replace('-', '年')}月预算（可选）`;renderCategoryManager();renderAccountManager();$('#settingsDialog').showModal()}
function renderBooks(){const list=$('#bookList');list.innerHTML=state.books.map(book=>{const hex=(book.color||'#444').replace('#',''),rgb=hex.length===6?[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)):[60,60,60],light=rgb[0]*.299+rgb[1]*.587+rgb[2]*.114>170;return`<button class="book-card ${book.id===activeBook().id?'active':''}" data-book-id="${book.id}" style="--book-color:${book.color};--book-text:${light?'#242424':'#fff'}"><i>¥</i><span>${book.name}</span>${book.id===activeBook().id?'<b>当前账本</b>':'<b>点此切换</b>'}</button>`}).join('')}
function openBooks(){renderBooks();$('#bookDialog').showModal()}
$('#bookButton').onclick=openBooks;
$('#navBooks').onclick=openBooks;
$('#bookList').onclick=e=>{const card=e.target.closest('[data-book-id]');if(!card)return;state.currentBookId=card.dataset.bookId;accountFilter='all';save();$('#bookDialog').close();render();toast(`已切换到${activeBook().name}`)};
$('#addBook').onclick=()=>{const name=$('#newBookName').value.trim(),color=$('#newBookColor').value;if(!name){toast('先填写账本名称');return}if(state.books.some(book=>book.name===name)){toast('这个账本已经有了');return}state.books.push({id:id(),name,color});state.currentBookId=state.books[state.books.length-1].id;$('#newBookName').value='';save();$('#bookDialog').close();render();toast('新账本已创建')};
$('#settingsButton').onclick=openSettings;$('#navSettings').onclick=openSettings;
$('#saveSettings').onclick=()=>{state.settings.currency=$('#currencyInput').value.trim()||'¥';state.monthlyBudgets[activeBook().id]??={};const value=$('#budgetInput').value;if(value)state.monthlyBudgets[activeBook().id][monthKey(currentMonth)]=value;else delete state.monthlyBudgets[activeBook().id][monthKey(currentMonth)];save();$('#settingsDialog').close();render();toast('本月预算已保存')};
$('#addCategory').onclick=()=>{const type=$('#newCategoryType').value,name=$('#newCategoryName').value.trim(),icon=$('#newCategoryIcon').value.trim()||'🏷️';if(!name){toast('先填写分类名称');return}if(categoryList(type).some(c=>c[0]===name)){toast('这个分类已经有了');return}state.categories[type].push([name,icon]);save();$('#newCategoryName').value='';renderCategoryManager();toast('已添加分类')};
for(const manager of [$('#expenseCategoryManager'),$('#incomeCategoryManager')])manager.onclick=e=>{const b=e.target.closest('button');if(!b)return;const {type,name}=b.dataset;state.categories[type]=categoryList(type).filter(c=>c[0]!==name);save();renderCategoryManager();toast(`已删除“${name}”，历史账目仍保留`)};
$('#addAccount').onclick=()=>{const name=$('#newAccountName').value.trim(),icon=$('#newAccountIcon').value.trim()||'💳';if(!name){toast('先填写账户名称');return}if(accountList().some(a=>a[0]===name)){toast('这个账户已经有了');return}state.accounts.push([name,icon]);save();$('#newAccountName').value='';renderAccountManager();render();toast('已添加账户')};
$('#accountManager').onclick=e=>{const b=e.target.closest('button');const name=b?.dataset.accountName;if(!name)return;state.accounts=accountList().filter(a=>a[0]!==name);if(accountFilter===name)accountFilter='all';save();renderAccountManager();render();toast('已删除账户，历史账目仍保留')};
$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Sunny记账备份-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('备份已导出')};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported.transactions))throw Error();state=imported;save();$('#settingsDialog').close();render();toast('备份导入成功')}catch{toast('这不是有效的简账备份文件')}e.target.value=''};
$('#filterButton').onclick=()=>$('#filterDialog').showModal();$('#filterOptions').onclick=e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;document.querySelectorAll('#filterOptions button').forEach(b=>b.classList.toggle('active',b===e.target));$('#filterDialog').close();render()};
$('#accountChips').onclick=e=>{const chip=e.target.closest('[data-account]');if(!chip)return;accountFilter=chip.dataset.account;render()};
let reportMode='month',chartPeriod='year',chartType='expense';
const totals=items=>({income:items.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),expense:items.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0)});
const reportYears=selectableYears;
function chartItems(){const items=state.transactions.filter(belongsToActiveBook),year=currentMonth.getFullYear(),today=new Date();if(chartPeriod==='year')return items.filter(t=>t.date.startsWith(String(year)));if(chartPeriod==='month')return items.filter(t=>t.date.startsWith(monthKey(currentMonth)));const start=new Date(today);start.setDate(today.getDate()-6);const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return items.filter(t=>t.date>=key(start)&&t.date<=key(today))}
function chartSeries(){const year=currentMonth.getFullYear(),today=new Date(),items=state.transactions.filter(belongsToActiveBook),sumFor=match=>items.filter(t=>t.type===chartType&&match(t)).reduce((s,t)=>s+t.amount,0);if(chartPeriod==='year')return Array.from({length:12},(_,i)=>({label:`${i+1}月`,value:sumFor(t=>t.date.startsWith(`${year}-${String(i+1).padStart(2,'0')}`))}));if(chartPeriod==='month'){const count=new Date(year,currentMonth.getMonth()+1,0).getDate();return Array.from({length:count},(_,i)=>({label:`${i+1}日`,value:sumFor(t=>t.date===`${monthKey(currentMonth)}-${String(i+1).padStart(2,'0')}`)}))}return Array.from({length:7},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-6+i);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return{label:`${d.getMonth()+1}/${d.getDate()}`,value:sumFor(t=>t.date===key)}})}
function drawRichTrend(){const series=chartSeries(),chart=$('#trendChart'),ctx=chart.getContext('2d'),peak=Math.max(...series.map(x=>x.value),0),max=Math.max(peak,1),ratio=Math.min(window.devicePixelRatio||1,2),cssWidth=Math.max(chart.clientWidth,280),cssHeight=190;chart.width=cssWidth*ratio;chart.height=cssHeight*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);const left=16,right=12,top=25,bottom=28,w=cssWidth-left-right,h=cssHeight-top-bottom;ctx.clearRect(0,0,cssWidth,cssHeight);ctx.strokeStyle='#e1e1e4';ctx.lineWidth=1;[0,.5,1].forEach(p=>{const y=top+h*p;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(cssWidth-right,y);ctx.stroke()});const color=chartType==='expense'?'#e1b600':'#20a477';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.lineJoin='round';ctx.beginPath();series.forEach((p,i)=>{const x=left+w*(series.length===1?0:i/(series.length-1)),y=top+h-(p.value/max)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();series.forEach((p,i)=>{const x=left+w*(series.length===1?0:i/(series.length-1)),y=top+h-(p.value/max)*h;ctx.fillStyle=p.value?color:'#fff';ctx.strokeStyle=color;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();ctx.stroke();const show=series.length<=12?i%2===0:i===0||i===series.length-1||i%7===0;if(show){ctx.fillStyle='#89898f';ctx.font='10px sans-serif';ctx.fillText(p.label.replace('日',''),Math.max(2,x-8),cssHeight-6)}});$('#trendHint').textContent=peak?`最高 ${money(peak)}`:'暂无数据'}
function renderBillRows(year){if(reportMode==='month'){const rows=Array.from({length:12},(_,i)=>{const month=11-i,items=state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)),sum=totals(items);return{label:`${month+1}月`,income:sum.income,expense:sum.expense,balance:sum.income-sum.expense,month}});$('#billTableHead').innerHTML='<span>月份</span><span>月收入</span><span>月支出</span><span>月结余</span>';$('#billRows').innerHTML=rows.map(r=>`<button class="bill-row" data-bill-month="${r.month}"><span>${r.label}</span><b>${money(r.income)}</b><b>${money(r.expense)}</b><b>${money(r.balance)}</b></button>`).join('')}else{const rows=reportYears().map(y=>{const sum=totals(state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(String(y))));return{year:y,income:sum.income,expense:sum.expense,balance:sum.income-sum.expense}});$('#billTableHead').innerHTML='<span>年份</span><span>年收入</span><span>年支出</span><span>年结余</span>';$('#billRows').innerHTML=rows.map(r=>`<button class="bill-row" data-bill-year="${r.year}"><span>${r.year}年</span><b>${money(r.income)}</b><b>${money(r.expense)}</b><b>${money(r.balance)}</b></button>`).join('')}}
function openReport(){const year=currentMonth.getFullYear(),yearItems=state.transactions.filter(t=>belongsToActiveBook(t)&&t.date.startsWith(String(year))),allItems=state.transactions.filter(belongsToActiveBook),shown=reportMode==='year'?allItems:reportMode==='chart'?chartItems():yearItems,sum=totals(shown);$('#reportYearPicker').innerHTML=reportYears().map(y=>`<option value="${y}" ${y===year?'selected':''}>${y}年</option>`).join('');$('#billPicker').hidden=reportMode==='year';$('#billPickerLabel').textContent=reportMode==='chart'?'图表年份':'账单年份';$('#reportEyebrow').textContent=reportMode==='chart'?'收支图表':reportMode==='year'?'年度总账':'年度月账单';$('#reportMonth').textContent=reportMode==='chart'?`${year}年图表分析`:reportMode==='year'?'全部年份账单':`${year}年账单`;$('#reportBalanceLabel').textContent=reportMode==='year'?'总结余':reportMode==='chart'?'所选时段结余':'年结余';$('#reportIncomeLabel').textContent=reportMode==='year'?'总收入':reportMode==='chart'?'时段收入':'年收入';$('#reportExpenseLabel').textContent=reportMode==='year'?'总支出':reportMode==='chart'?'时段支出':'年支出';$('#reportCountLabel').textContent=reportMode==='year'?'有记录年份':'记账天数';$('#reportBalance').textContent=money(sum.income-sum.expense);$('#reportIncome').textContent=money(sum.income);$('#reportExpense').textContent=money(sum.expense);$('#reportDays').textContent=reportMode==='year'?`${new Set(shown.map(t=>t.date.slice(0,4))).size} 年`:`${new Set(shown.map(t=>t.date)).size} 天`;$('#trendWrap').hidden=reportMode!=='chart';$('#billTableWrap').hidden=reportMode==='chart';$('#rankWrap').hidden=reportMode!=='chart';if(reportMode!=='chart')renderBillRows(year);else{const rankedItems=shown,typeTotal=rankedItems.filter(t=>t.type===chartType).reduce((s,t)=>s+t.amount,0),ranked=Object.entries(rankedItems.filter(t=>t.type===chartType).reduce((map,t)=>{map[t.category]=(map[t.category]||0)+t.amount;return map},{})).sort((a,b)=>b[1]-a[1]);$('#rankWrap h3').textContent=chartType==='expense'?'支出排行榜':'收入排行榜';$('#reportRanks').innerHTML=ranked.length?ranked.slice(0,10).map(([name,value])=>`<div class="report-rank"><i>${iconFor(chartType,name)}</i><div><b>${name}</b><div class="report-rank-bar"><span style="width:${Math.round(value/typeTotal*100)}%"></span></div></div><strong>${money(value)}</strong></div>`).join(''):'<p class="settings-note">这个时间段还没有记录。</p>';requestAnimationFrame(drawRichTrend)}document.querySelectorAll('[data-report-mode]').forEach(b=>b.classList.toggle('active',b.dataset.reportMode===reportMode));const dialog=$('#reportDialog');if(!dialog.open)dialog.showModal()}
document.querySelectorAll('[data-report-mode]').forEach(b=>b.onclick=()=>{reportMode=b.dataset.reportMode;openReport()});
$('#reportYearPicker').onchange=e=>{currentMonth.setFullYear(Number(e.target.value));openReport()};
$('#billRows').onclick=e=>{const row=e.target.closest('[data-bill-month],[data-bill-year]');if(!row)return;if(row.dataset.billMonth!==undefined){currentMonth.setMonth(Number(row.dataset.billMonth));listMode='month';$('#reportDialog').close();render();toast(`已打开${currentMonth.getFullYear()}年${currentMonth.getMonth()+1}月`)}else{currentMonth.setFullYear(Number(row.dataset.billYear));reportMode='month';openReport()}};
document.querySelectorAll('[data-chart-period]').forEach(b=>b.onclick=()=>{chartPeriod=b.dataset.chartPeriod;document.querySelectorAll('[data-chart-period]').forEach(x=>x.classList.toggle('active',x===b));openReport()});
$('#chartType').onchange=e=>{chartType=e.target.value;openReport()};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='report')openReport()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');render();
